// -----------------------------------------------------------------------------------------------------------
// Copyright (C) AVIN SYSTEMS PVT LTD 2022 - All Rights Reserved Reproduction, distribution and utilization
// of this document as well as the communication of its contents to others without explicit authorization is
// prohibited. Offenders will be held liable for the payment of damages.
// -----------------------------------------------------------------------------------------------------------
// File Name   : ara_com_main-statemanagerexe.cpp
//
// Purpose     : Implementation of file ara_com_main-statemanagerexe.cpp
// -----------------------------------------------------------------------------------------------------------
// CODE GENERATED BY        : CM Code Generator
//
// CODE GENERATOR VERSION   : 2.0.0.202104141514
//
// GENERATED ON             : 2021-04-29T12:14:45+05:30
// -----------------------------------------------------------------------------------------------------------

namespace ara
{
namespace com
{
namespace internal
{
namespace runtime
{
void Initialize()
{
}

} // namespace runtime
} // namespace internal
} // namespace com
} // namespace ara
